services:
  champ-nvidia-ubuntu: # Service for running CHAMP w/ NVIDIA GPU on an Ubuntu host
    extends: # Config for NVIDIA GPU on Ubuntu host
      file: ./docker/ros_docker/docker/core-compose.yaml
      service: base-nvidia-ubuntu

    build:
      context: .
      dockerfile: champ-noetic

    image: bennedh/champ-noetic:nvidia-ubuntu

    volumes: # Mount this repository (a ROS workspace) into the container
      - .:/docker/champ
