services:
  # Base service providing access to Docker via command-line
  base-cli:
    environment:
      # Nice-to-have environment variables
      - TERM # Pass the TERM environment variable specifying the terminal type
      - color_prompt=yes # Provide a colored prompt in the container

    volumes:
      - /etc/localtime:/etc/localtime:ro # Sync container timezone with the host (read-only)

    stdin_open: true # docker run -i
    tty: true # docker run -t

  # Base service supporting GUIs on Ubuntu hosts
  base-gui-ubuntu:
    extends:
      service: base-cli

    environment:
      # Environment variables to support in-container GUIs on an Ubuntu host
      - DISPLAY # Pass the DISPLAY environment variable for X11 forwarding
      - QT_X11_NO_MITSHM=1 # Prevent Qt apps in the container from using X11's MIT-SHM extension

    devices:
      - "/dev/dri:/dev/dri" # Map the host's Direct Rendering Infrastructure (DRI) into the container

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Mount the X11 Unix socket to support GUIs

  # Base service supporting GUIs on macOS hosts
  base-gui-mac-os:
    extends:
      service: base-cli

    environment:
      # Environment variables to support in-container GUIs on a macOS host
      - DISPLAY=docker.for.mac.host.internal:0

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Mount the X11 Unix socket to support GUIs
